export const dataCymbals = [
    { menu: 'Comida', categorie: 'Entradas', name: 'Crudo de atun', status: 'true', price: '310', description: 'Con recado negro y miso' },
    { menu: 'Comida', categorie: 'Entradas', name: 'Callo de aguachile', status: 'true', price: '375', description: 'Aguachile rojo de chiles oaxaqueños fermentados y mayonesa de ostion' },
    { menu: 'Comida', categorie: 'Entradas', name: 'Tiradito de pescado', status: 'true', price: '250', description: 'Pepino,cebolla morada, salsa verde de salicornia y mayonesa california' },
    { menu: 'Comida', categorie: 'Entradas', name: 'Jaiba de concha suave', status: 'true', price: '320', description: 'En salsa thermidor,jaiba frita,chocrut y chetextle' },
    { menu: 'Comida', categorie: 'Entradas', name: 'Tuetanos al grill', status: 'true', price: '350', description: 'Cebolla curtida y aguacate' },
    { menu: 'Comida', categorie: 'Entradas', name: 'Tlacoyos de pulpo y camaron', status: 'true', price: '280', description: 'Pulpo y camaron al ajillo' },
    { menu: 'Comida', categorie: 'Entradas', name: 'Bao de pato en salsa agridulce', status: 'true', price: '250', description: 'Salsa agridulce de chile ancho,pepino y cilantro' },
    { menu: 'Comida', categorie: 'Ensaladas y sopas', name: 'Ensalada betabel', status: 'true', price: '220', description: 'Burrata,betabel,fresa,tomate,nuez y vinagreta de frambuesa' },
    { menu: 'Comida', categorie: 'Ensaladas y sopas', name: 'Ensalada verde', status: 'true', price: '160', description: 'Manzana,uva,pepino,piñon y vinagreta de limon con miel' },
    { menu: 'Comida', categorie: 'Ensaladas y sopas', name: 'Sopa de hongos', status: 'true', price: '180', description: 'Amaranto,guajillo y epazote' },
    { menu: 'Comida', categorie: 'Ensaladas y sopas', name: 'Bisque de camaron', status: 'true', price: '240', description: 'Sofrito de pimientos con chile pasilla mize' },
    { menu: 'Comida', categorie: 'Ensaladas y sopas', name: 'Crema de tomate', status: 'true', price: '170', description: 'Sazonada con chicharron de cerdo' },
    { menu: 'Comida', categorie: 'Para compartir', name: 'Tabla de quesos', status: 'true', price: '395', description: 'Quesos de la region, aceitunas,charcuteria y pan de la casa' },
    { menu: 'Comida', categorie: 'Para compartir', name: 'Pezcado Zarandeado', status: 'true', price: '1250', description: 'A las brazas, ensalada y vegetales' },
    { menu: 'Comida', categorie: 'Para compartir', name: 'Tomahawk', status: 'true', price: '2200', description: 'Aligot y vegetales' },
    { menu: 'Comida', categorie: 'Para compartir', name: 'Lengua de res', status: 'true', price: '440', description: 'Salsa verde para taquear' },
    { menu: 'Comida', categorie: 'Platos Fuertes', name: 'Pesca del dia ', status: 'true', price: '420', description: 'Gremolata de algas y emulsion de chiles' },
    { menu: 'Comida', categorie: 'Platos Fuertes', name: 'Pulpo adobado', status: 'true', price: '450', description: 'Adobado con achiote y miso,esferas de papa, pure de zanahoria' },
    { menu: 'Comida', categorie: 'Platos Fuertes', name: 'Cola de langosta', status: 'true', price: '720', description: 'Con risotto de salsa de langosta' },
    { menu: 'Comida', categorie: 'Platos Fuertes', name: 'Colifor rostizada', status: 'true', price: '250', description: 'Aceite de chintextle, pipian de brocoli, chayote curtido, cremoso de pistache' },
    { menu: 'Comida', categorie: 'Platos Fuertes', name: 'Magret de pato', status: 'true', price: '365', description: 'Termino medio,mole negro y betabel' },
    { menu: 'Comida', categorie: 'Platos Fuertes', name: 'Pollito lechal asado', status: 'true', price: '390', description: 'Pure de camate, garbanzos, alubias , quinoa y vinagreta de chicatana' },
    { menu: 'Comida', categorie: 'Platos Ffuertes', name: 'Lechon confitado', status: 'true', price: '425', description: 'Mole encacahuatado y vegetales en escabeche' },
    { menu: 'Comida', categorie: 'Platos Fuertes', name: 'Chamorro de borrego', status: 'true', price: '690', description: 'Braseado con pure de coliflor' },
    { menu: 'Comida', categorie: 'Platos Fuertes', name: 'New York', status: 'true', price: '890', description: 'Al grill con aligot y vegetales' },
    { menu: 'Comida', categorie: 'Postres', name: 'Selva negra', status: 'true', price: '220', description: 'Mouse de chocolate, cujriente de cacao y cumbre de brownie' },
    { menu: 'Comida', categorie: 'Postres', name: 'Limon real', status: 'true', price: '180', description: 'Limon confitado, ganache de limon  y cumbre de mantequilla' },
    { menu: 'Comida', categorie: 'Postres', name: 'Tarta rustica', status: 'true', price: '180', description: 'Galette de fruta de temporada' },
    { menu: 'Comida', categorie: 'Postres', name: 'Baklava', status: 'true', price: '180', description: 'Pasta fillo , nuez, canela y mantequilla' },
    { menu: 'Comida', categorie: 'Postres', name: 'Cafe lechero', status: 'true', price: '175', description: 'Panna cotta de leche y jarabe de cafe veracruzano' },
    { menu: 'Desayunos', categorie: 'Para despertar', name: 'Bowl de fruta con yogurt', status: 'true', price: '115', description: 'yogurt de frutas , frutas de temporada, granola y miel de abeja' },
    { menu: 'Desayunos', categorie: 'Para despertar', name: 'Plato de frutas con ricotta', status: 'true', price: '145', description: 'Queso ricotta, fruta de temporada y nuez caramelizada' },
    { menu: 'Desayunos', categorie: 'Para despertar', name: 'Avocado Toast', status: 'true', price: '125', description: 'Pan de masa madre, aguacate , tomate y huevo pochado' },
    { menu: 'Desayunos', categorie: 'Para Compartir', name: 'Borrego tatemado', status: 'true', price: '270', description: 'Orden de borrego tatemado,frijoles,queso fresco y tortillas' },
    { menu: 'Desayunos', categorie: 'Para despertar', name: 'Shakshuka', status: 'true', price: '200', description: 'Vegetales salteados en salsa de tomado,aceite de oliva y especias, huevos estrellados y queso de cabra ' },
    { menu: 'Desayunos', categorie: 'Omelets', name: 'A la mexicana', status: 'true', price: '270', description: 'Cebolla,tomate, chile california, queso y salsa de frijol' },
    { menu: 'Desayunos', categorie: 'Omelets', name: 'Hongos', status: 'true', price: '220', description: 'Bañado en salsa de quesos, champiñones confitados , esparragos y tomate' },
    { menu: 'Desayunos', categorie: 'Omelets', name: 'Camaron', status: 'true', price: '280', description: 'Sofrito de camaron con tocino y queso, ensalada y aguacate' },
    { menu: 'Desayunos', categorie: 'Omelets', name: 'Costilla', status: 'true', price: '240', description: 'Salsa roja , costilla de res braseada, queso y frijoles' },
    { menu: 'Desayunos', categorie: 'Chilaquiles', name: 'Rojos', status: 'true', price: '140', description: 'Salsa roja, queso cotija, cebolla y huevo al gusto con frijoles' },
    { menu: 'Desayunos', categorie: 'Chilaquiles', name: 'Hongos', status: 'true', price: '140', description: 'Salsa roja, queso cotija, cebolla y huevo al gusto con frijoles' },
    { menu: 'Desayunos', categorie: 'Chilaquiles', name: 'Camaron', status: 'true', price: '140', description: 'SSalsa roja, queso cotija, cebolla y huevo al gusto con frijoles' },
    { menu: 'Desayunos', categorie: 'Lo Dulce', name: 'Wafles', status: 'true', price: '210', description: 'Salsa toffe, helado espresso y fruta' },
    { menu: 'Desayunos', categorie: 'Lo Dulce', name: 'Pan fancres', status: 'true', price: '110', description: 'Wafle , miel , almendra y fruta' },
    { menu: 'Desayunos', categorie: 'Lo Dulce', name: 'Canasta de pan', status: 'true', price: '110', description: 'Pan dulce hecho en casa' },
    { menu: 'Desayunos', categorie: 'Bebidas Sin Alcohol', name: 'Piñada', status: 'true', price: '120', description: '' },
    { menu: 'Bebidas', categorie: 'Bebidas Sin Alcohol', name: 'Limonada natural', status: 'true', price: '45', description: '' },
    { menu: 'Bebidas', categorie: 'Bebidas Sin Alcohol', name: 'Limonada mineral', status: 'true', price: '45', description: '' },
    { menu: 'Bebidas', categorie: 'Bebidas Sin Alcohol', name: 'Naranjada', status: 'true', price: '120', description: '' },
    { menu: 'Bebidas', categorie: 'Bebidas Sin Alcohol', name: 'Cocacola', status: 'true', price: '120', description: '' },
    { menu: 'Bebidas', categorie: 'Bebidas Sin Alcohol', name: 'Sprite', status: 'true', price: '120', description: '' },
    { menu: 'Bebidas', categorie: 'Bebidas Sin Alcohol', name: 'Piñada', status: 'true', price: '120', description: '' },
    { menu: 'Bebidas', categorie: 'Bebidas Sin Alcohol', name: 'Piñada', status: 'true', price: '120', description: '' },
    { menu: 'Cafeteria', categorie: 'Cafe', name: 'Espresso', status: 'true', price: '50', description: '' },
    { menu: 'Cafeteria', categorie: 'Cafe', name: 'Cafe americano', status: 'true', price: '50', description: '' },
    { menu: 'Cafeteria', categorie: 'Cafe', name: 'Latte', status: 'true', price: '50', description: '' },
    { menu: 'Cafeteria', categorie: 'Cafe', name: 'Capuccino', status: 'true', price: '50', description: '' },
    { menu: 'Cafeteria', categorie: 'Cafe', name: 'Mocha', status: 'true', price: '50', description: '' },
    { menu: 'Cafeteria', categorie: 'Té', name: 'Negro', status: 'true', price: '50', description: '' },
    { menu: 'Cafeteria', categorie: 'Té', name: 'Verde', status: 'true', price: '50', description: '' },
    { menu: 'Cafeteria', categorie: 'Té', name: 'Manzanilla', status: 'true', price: '50', description: '' },
    { menu: 'Desayunos', categorie: 'Té', name: 'Jazmin', status: 'true', price: '50', description: '' },
    { menu: 'Mixologia', categorie: 'Mixologia de la casa', name: 'Carajillo', status: 'true', price: '210', description: 'Licor 43, cerveza artesanal y espresso' },
    { menu: 'Mixologia', categorie: 'Mixologia de la casa', name: 'La chingadera', status: 'true', price: '210', description: 'Jarabe de gengibre, agua tonica y cocacola' },
    { menu: 'Mixologia', categorie: 'Mixologia de la casa', name: 'La chingadera', status: 'true', price: '210', description: 'Jarabe de gengibre, agua tonica y cocacola' },
    { menu: 'Mixologia', categorie: 'Mixologia de la casa', name: 'La chingadera', status: 'true', price: '210', description: 'Jarabe de gengibre, agua tonica y cocacola' }, { menu: 'Mixologia', categorie: 'Mixologia de la casa', name: 'La chingadera', status: 'true', price: '210', description: 'Jarabe de gengibre, agua tonica y cocacola' }, { menu: 'Mixologia', categorie: 'Mixologia de la casa', name: 'La chingadera', status: 'true', price: '210', description: 'Jarabe de gengibre, agua tonica y cocacola' }, { menu: 'Mixologia', categorie: 'Mixologia de la casa', name: 'La chingadera', status: 'true', price: '210', description: 'Jarabe de gengibre, agua tonica y cocacola' },
    { menu: 'Mixologia', categorie: 'Coctelería Clásica', name: 'Abe', status: 'true', price: '190', description: '' },
    { menu: 'Mixologia', categorie: 'Coctelería Clásica', name: 'Abe', status: 'true', price: '190', description: '' },
    { menu: 'Mixologia', categorie: 'Coctelería Clásica', name: 'Abe', status: 'true', price: '190', description: '' },
    { menu: 'Mixologia', categorie: 'Coctelería Clásica', name: 'Abe', status: 'true', price: '190', description: '' },
    { menu: 'Mixologia', categorie: 'Coctelería Clásica', name: 'Abe', status: 'true', price: '190', description: '' },
    { menu: 'Mixologia', categorie: 'Coctelería Clásica', name: 'Abe', status: 'true', price: '190', description: '' },
    { menu: 'Mixologia', categorie: 'Coctelería Clásica', name: 'Abe', status: 'true', price: '190', description: '' },
    { menu: 'Mixologia', categorie: 'Coctelería Clásica', name: 'Abe', status: 'true', price: '190', description: '' },
    { menu: 'Mixologia', categorie: 'Coctelería Clásica', name: 'Abe', status: 'true', price: '190', description: '' },
    { menu: 'Mixologia', categorie: 'Licores Fuertes', name: '1800', status: 'true', price: '2700', description: 'shot:160' },
    { menu: 'Mixologia', categorie: 'Licores Fuertes', name: '1800', status: 'true', price: '2700', description: 'shot:160' },
    { menu: 'Mixologia', categorie: 'Licores Fuertes', name: '1800', status: 'true', price: '2700', description: 'shot:160' },
    { menu: 'Mixologia', categorie: 'Licores Fuertes', name: '1800', status: 'true', price: '2700', description: 'shot:160' },
    { menu: 'Mixologia', categorie: 'Licores Fuertes', name: '1800', status: 'true', price: '2700', description: 'shot:160' },
    { menu: 'Mixologia', categorie: 'Licores Fuertes', name: '1800', status: 'true', price: '2700', description: 'shot:160' },
    { menu: 'Mixologia', categorie: 'Licores Fuertes', name: '1800', status: 'true', price: '2700', description: 'shot:160' },
    { menu: 'Mixologia', categorie: 'Licores Fuertes', name: '1800', status: 'true', price: '2700', description: 'shot:160' },
    { menu: 'Mixologia', categorie: 'Licores Fuertes', name: '1800', status: 'true', price: '2700', description: 'shot:160' },
    { menu: 'Mixologia', categorie: 'Licores Fuertes', name: '1800', status: 'true', price: '2700', description: 'shot:160' },
    { menu: 'Mixologia', categorie: 'Licores Fuertes', name: '1800', status: 'true', price: '2700', description: 'shot:160' },
    { menu: 'Mixologia', categorie: 'Licores Fuertes', name: '1800', status: 'true', price: '2700', description: 'shot:160' },
    { menu: 'Vino', categorie: 'Premium', name: 'Negro', status: 'true', price: '50', description: '' },
    { menu: 'Cafeteria', categorie: 'Té', name: 'Verde', status: 'true', price: '50', description: '' },
    { menu: 'Cafeteria', categorie: 'Té', name: 'Manzanilla', status: 'true', price: '50', description: '' },
    { menu: 'Desayunos', categorie: 'Té', name: 'Jazmin', status: 'true', price: '50', description: '' },
    { menu: 'Vino', categorie: 'Premium', name: 'Negro', status: 'true', price: '50', description: '' },
    { menu: 'Cafeteria', categorie: 'Té', name: 'Verde', status: 'true', price: '50', description: '' },
    { menu: 'Cafeteria', categorie: 'Té', name: 'Manzanilla', status: 'true', price: '50', description: '' },
    { menu: 'Desayunos', categorie: 'Té', name: 'Jazmin', status: 'true', price: '50', description: '' },
    { menu: 'Vino', categorie: 'Premium', name: 'Negro', status: 'true', price: '50', description: '' },
    { menu: 'Cafeteria', categorie: 'Té', name: 'Verde', status: 'true', price: '50', description: '' },
    { menu: 'Cafeteria', categorie: 'Té', name: 'Manzanilla', status: 'true', price: '50', description: '' },
    { menu: 'Desayunos', categorie: 'Té', name: 'Jazmin', status: 'true', price: '50', description: '' },
]