

export const listaDatos = [{ menu: "Comida", categorie: "Ensaladas y sopas", name: 'Ensalada betabel', price: '220', status: 'active', description: 'Burrata,betabel,fresa,tomate,nuez y vinagreta de frambuesa' },
{ menu: "Comida", categorie: "Ensaladas y sopas", name: 'Ensalada verde', price: '160', status: 'active', description: 'Manzana,uva,pepino,piñon y vinagreta de limon con miel' },
{ menu: "Comida", categorie: "Ensaladas y sopas", name: 'Sopa de hongos', price: '180', status: 'active', description: 'Amaranto,guajillo y epazote' },
{ menu: "Comida", categorie: "Ensaladas y sopas", name: 'Bisque de camaron', price: '240', status: 'active', description: 'Sofrito de pimientos con chile pasilla mize' },
{ menu: "Comida", categorie: "Ensaladas y sopas", name: 'Crema de tomate', price: '170', status: 'active', description: 'Sazonada con chicharron de cerdo' },
{ menu: "Comida", categorie: "Para compartir", name: 'Tabla de quesos', price: '395', status: 'active', description: 'Quesos de la region, aceitunas,charcuteria y pan de la casa' },
{ menu: "Comida", categorie: "Para compartir", name: 'Pezcado Zarandeado', price: '1250', status: 'active', description: 'A las brazas, ensalada y vegetales' },
{ menu: "Comida", categorie: "Para compartir", name: 'Tomahawk', price: '2200', status: 'active', description: 'Aligot y vegetales' },
{ menu: "Comida", categorie: "Para compartir", name: 'Lengua de res', price: '440', status: 'active', description: 'Salsa verde para taquear' },
{ menu: "Comida", categorie: "Platos Fuertes", name: 'Pesca del dia ', price: '420', status: 'active', description: 'Gremolata de algas y emulsion de chiles' },
{ menu: "Comida", categorie: "Platos Fuertes", name: 'Pulpo adobado', price: '450', status: 'active', description: 'Adobado con achiote y miso,esferas de papa, pure de zanahoria' },
{ menu: "Comida", categorie: "Platos Fuertes", name: 'Cola de langosta', price: '720', status: 'active', description: 'Con risotto de salsa de langosta' },
{ menu: "Comida", categorie: "Platos Fuertes", name: 'Colifor rostizada', price: '250', status: 'active', description: 'Aceite de chintextle, pipian de brocoli, chayote curtido, cremoso de pistache' },
{ menu: "Comida", categorie: "Platos Fuertes", name: 'Magret de pato', price: '365', status: 'active', description: 'Termino medio,mole negro y betabel' },
{ menu: "Comida", categorie: "Platos Fuertes", name: 'Pollito lechal asado', price: '390', status: 'active', description: 'Pure de camate, garbanzos, alubias , quinoa y vinagreta de chicatana' },
{ menu: "Comida", categorie: "Platos Fuertes", name: 'Lechon confitado', price: '425', status: 'active', description: 'Mole encacahuatado y vegetales en escabeche' },
{ menu: "Comida", categorie: "Platos Fuertes", name: 'Chamorro de borrego', price: '690', status: 'active', description: 'Braseado con pure de coliflor' },
{ menu: "Comida", categorie: "Platos Fuertes", name: 'New York', price: '890', status: 'active', description: 'Al grill con aligot y vegetales' },
{ menu: "Comida", categorie: "Postres", name: 'Selva negra', price: '220', status: 'active', description: 'Mouse de chocolate, cujriente de cacao y cumbre de brownie' },
{ menu: "Comida", categorie: "Postres", name: 'Limon real', price: '180', status: 'active', description: 'Limon confitado, ganache de limon  y cumbre de mantequilla' },
{ menu: "Comida", categorie: "Postres", name: 'Tarta rustica', price: '180', status: 'active', description: 'Galette de fruta de temporada' },
{ menu: "Comida", categorie: "Postres", name: 'Baklava', price: '180', status: 'active', description: 'Pasta fillo , nuez, canela y mantequilla' },
{ menu: "Comida", categorie: "Postres", name: 'Cafe lechero', price: '175', status: 'active', description: 'Panna cotta de leche y jarabe de cafe veracruzano' },
{ menu: "Desayunos", categorie: "Para despertar", name: 'Bowl de fruta con yogurt', price: '115', status: 'active', description: 'yogurt de frutas , frutas de temporada, granola y miel de abeja' },
{ menu: "Desayunos", categorie: "Para despertar", name: 'Plato de frutas con ricotta', price: '145', status: 'active', description: 'Queso ricotta, fruta de temporada y nuez caramelizada' },
{ menu: "Desayunos", categorie: "Para despertar", name: 'Avocado Toast', price: '125', status: 'active', description: 'Pan de masa madre, aguacate , tomate y huevo pochado' },
{ menu: "Desayunos", categorie: "Para compartir", name: 'Borrego tatemado', price: '270', status: 'active', description: 'Orden de borrego tatemado,frijoles,queso fresco y tortillas' },
{ menu: "Desayunos", categorie: "Para despertar", name: 'Shakshuka', price: '200', status: 'active', description: 'Vegetales salteados en salsa de tomado,aceite de oliva y especias, huevos estrellados y queso de cabra ' },
{ menu: "Desayunos", categorie: "Omelets", name: 'A la mexicana', price: '270', status: 'active', description: 'Cebolla,tomate, chile california, queso y salsa de frijol' },
{ menu: "Desayunos", categorie: "Omelets", name: 'Hongos', price: '220', status: 'active', description: 'Bañado en salsa de quesos, champiñones confitados , esparragos y tomate' },
{ menu: "Desayunos", categorie: "Omelets", name: 'Camaron', price: '280', status: 'active', description: 'Sofrito de camaron con tocino y queso, ensalada y aguacate' },
{ menu: "Desayunos", categorie: "Omelets", name: 'Costilla', price: '240', status: 'active', description: 'Salsa roja , costilla de res braseada, queso y frijoles' },
{ menu: "Desayunos", categorie: "Chilaquiles", name: 'Rojos', price: '140', status: 'active', description: 'Salsa roja, queso cotija, cebolla y huevo al gusto con frijoles' },
{ menu: "Desayunos", categorie: "Chilaquiles", name: 'Hongos', price: '140', status: 'active', description: 'Salsa roja, queso cotija, cebolla y huevo al gusto con frijoles' },
{ menu: "Desayunos", categorie: "Chilaquiles", name: 'Camaron', price: '140', status: 'active', description: 'SSalsa roja, queso cotija, cebolla y huevo al gusto con frijoles' },
{ menu: "Desayunos", categorie: "Lo Dulce", name: 'Wafles', price: '210', status: 'active', description: 'Salsa toffe, helado espresso y fruta' },
{ menu: "Desayunos", categorie: "Lo Dulce", name: 'Pan fancres', price: '110', status: 'active', description: 'Wafle , miel , almendra y fruta' },
{ menu: "Desayunos", categorie: "Lo Dulce", name: 'Canasta de pan', price: '110', status: 'active', description: 'Pan dulce hecho en casa' },
{ menu: "Desayunos", categorie: "Bebidas Sin Alcohol", name: 'Piñada', price: '120', status: 'active', description: '' },
{ menu: "Bebidas", categorie: "Bebidas Sin Alcohol", name: 'Limonada natural', price: '45', status: 'active', description: '' },
{ menu: "Bebidas", categorie: "Bebidas Sin Alcohol", name: 'Limonada mineral', price: '45', status: 'active', description: '' },
{ menu: "Bebidas", categorie: "Bebidas Sin Alcohol", name: 'Naranjada', price: '120', status: 'active', description: '' },
{ menu: "Bebidas", categorie: "Bebidas Sin Alcohol", name: 'Cocacola', price: '120', status: 'active', description: '' },
{ menu: "Bebidas", categorie: "Bebidas Sin Alcohol", name: 'Sprite', price: '120', status: 'active', description: '' },
{ menu: "Bebidas", categorie: "Bebidas Sin Alcohol", name: 'Piñada', price: '120', status: 'active', description: '' },
{ menu: "Bebidas", categorie: "Bebidas Sin Alcohol", name: 'Piñada', price: '120', status: 'active', description: '' },
{ menu: "Cafeteria", categorie: "Cafe", name: 'Espresso', price: '50', status: 'active', description: '' },
{ menu: "Cafeteria", categorie: "Cafe", name: 'Cafe americano', price: '50', status: 'active', description: '' },
{ menu: "Cafeteria", categorie: "Cafe", name: 'Latte', price: '50', status: 'active', description: '' },
{ menu: "Cafeteria", categorie: "Cafe", name: 'Capuccino', price: '50', status: 'active', description: '' },
{ menu: "Cafeteria", categorie: "Cafe", name: 'Mocha', price: '50', status: 'active', description: '' },
{ menu: "Cafeteria", categorie: "Té", name: 'Negro', price: '50', status: 'active', description: '' },
{ menu: "Cafeteria", categorie: "Té", name: 'Verde', price: '50', status: 'active', description: '' },
{ menu: "Cafeteria", categorie: "Té", name: 'Manzanilla', price: '50', status: 'active', description: '' },
{ menu: "Desayunos", categorie: "Té", name: 'Jazmin', price: '50', status: 'active', description: '' },
{ menu: "Mixologia", categorie: "Mixologia de la casa", name: 'Carajillo', price: '210', status: 'active', description: 'Licor 43, cerveza artesanal y espresso' },
{ menu: "Mixologia", categorie: "Mixologia de la casa", name: 'El mictlan', price: '210', status: 'active', description: 'Jarabe de gengibre, agua tonica y cocacola' },
{ menu: "Mixologia", categorie: "Mixologia de la casa", name: 'La chingadera', price: '210', status: 'active', description: 'Jarabe de gengibre, agua tonica y cocacola' },
{ menu: "Mixologia", categorie: "Mixologia de la casa", name: 'Mezcalito de la casa', price: '210', status: 'active', description: 'Jarabe de gengibre, agua tonica y cocacola' },
{ menu: "Mixologia", categorie: "Mixologia de la casa", name: 'Ruby Mezcal', price: '210', status: 'active', description: 'Jarabe de gengibre, agua tonica y cocacola' },
{ menu: "Mixologia", categorie: "Mixologia de la casa", name: 'Pink Panther', price: '210', status: 'active', description: 'Jarabe de gengibre, agua tonica y cocacola' },
{ menu: "Mixologia", categorie: "Mixologia de la casa", name: 'Blue Summer', price: '210', status: 'active', description: 'Jarabe de gengibre, agua tonica y cocacola' },
{ menu: "Mixologia", categorie: "Coctelería Clásica", name: 'Abc', price: '190', status: 'active', description: '' },
{ menu: "Mixologia", categorie: "Coctelería Clásica", name: 'Aperol', price: '190', status: 'active', description: '' },
{ menu: "Mixologia", categorie: "Coctelería Clásica", name: 'Blody Mary', price: '190', status: 'active', description: '' },
{ menu: "Mixologia", categorie: "Coctelería Clásica", name: 'Abe', price: '190', status: 'active', description: '' },
{ menu: "Mixologia", categorie: "Coctelería Clásica", name: 'Charro Negro', price: '190', status: 'active', description: '' },
{ menu: "Mixologia", categorie: "Coctelería Clásica", name: 'Cuba', price: '190', status: 'active', description: '' },
{ menu: "Mixologia", categorie: "Coctelería Clásica", name: 'Gin tonic', price: '190', status: 'active', description: '' },
{ menu: "Mixologia", categorie: "Coctelería Clásica", name: 'Martini Sucio', price: '190', status: 'active', description: '' },
{ menu: "Mixologia", categorie: "Coctelería Clásica", name: 'Pina colada', price: '190', status: 'active', description: '' },
{ menu: "Mixologia", categorie: "Licores Fuertes", name: '1800 añejo', price: '2700', status: 'active', description: 'shot:160' },
{ menu: "Mixologia", categorie: "Licores Fuertes", name: 'Don julio 70', price: '2400', status: 'active', description: 'shot:160' },
{ menu: "Mixologia", categorie: "Licores Fuertes", name: 'Herradura Añejo', price: '4500', status: 'active', description: 'shot:160' },
{ menu: "Mixologia", categorie: "Licores Fuertes", name: 'Jose cuervo', price: '1900', status: 'active', description: 'shot:160' },
{ menu: "Mixologia", categorie: "Licores Fuertes", name: 'Patron Silver', price: '1250', status: 'active', description: 'shot:160' },
{ menu: "Mixologia", categorie: "Licores Fuertes", name: 'Maestro Dobel', price: '2300', status: 'active', description: 'shot:160' },
{ menu: "Mixologia", categorie: "Licores Fuertes", name: 'Fireball', price: '1500', status: 'active', description: 'shot:160' },
{ menu: "Mixologia", categorie: "Licores Fuertes", name: 'Etiqueta Negra', price: '2000', status: 'active', description: 'shot:160' },
{ menu: "Mixologia", categorie: "Licores Fuertes", name: 'Jim Beam', price: '1800', status: 'active', description: 'shot:160' },
{ menu: "Mixologia", categorie: "Licores Fuertes", name: 'Martell', price: '1350', status: 'active', description: 'shot:160' },
{ menu: "Mixologia", categorie: "Licores Fuertes", name: 'Hennesy', price: '1100', status: 'active', description: 'shot:160' },
{ menu: "Mixologia", categorie: "Licores Fuertes", name: 'Hypnotic', price: '4000', status: 'active', description: 'shot:160' },
{ menu: 'Vino', categorie: "Premium", name: 'Sto Tomas Duetto', price: '1950', status: 'active', description: '60% tempranillo 40% cabernet' },
{ menu: 'Vino', categorie: "Premium", name: 'Sto Tomas Unico', price: '1950', status: 'active', description: '65% cabernet 35% merlot' },
{ menu: 'Vino', categorie: "Premium", name: 'Vinia Abril J.Alberich Nebiolo', price: '1950', status: 'active', description: '100% nebiolo' },
{ menu: 'Vino', categorie: "Reserva", name: 'Ojo azul Cabernet Franc', price: '900', status: 'active', description: '100% Cabenet Franc' },
{ menu: 'Vino', categorie: "Reserva", name: 'EMV Nietos', price: '900', status: 'active', description: 'Cabernet Sauvignon,Merlot y Cabernet Franc' },
{ menu: 'Vino', categorie: "Reserva", name: 'Vinia Abril Salud y Republica', price: '950', status: 'active', description: 'Nebiolo y Merlot' },
{ menu: 'Vino', categorie: "Reserva", name: 'Solar Fortun O positivo', price: '940', status: 'active', description: '60% Cabernet Sauvignon 40% syrah' },
{ menu: 'Vino', categorie: "Reserva", name: 'Baron Balche Reseva Especial', price: '1300', status: 'active', description: 'Cabernet Franc, Merlot y Syrah' },

{ menu: 'Vino', categorie: "Crianza", name: 'Ojo Azul Malbec Cabernet', price: '620', status: 'active', description: '60% Malbec, 40% Cabernet Sauvignon' },
{ menu: 'Vino', categorie: "Crianza", name: 'Ojo Azul Merlot', price: '610', status: 'active', description: '100% Merlot' },
{ menu: 'Vino', categorie: "Crianza", name: 'EMV Cabernet Sauvignon', price: '850', status: 'active', description: '100% Cabernet Sauvignon' },
{ menu: 'Vino', categorie: "Crianza", name: 'EMV Armonia de tintos', price: '610', status: 'active', description: 'Merlot,Cabernet Sauvignon , Shiraz y Cabernet Franc' },
{ menu: 'Vino', categorie: "Crianza", name: 'Vinia Emiliana Primo Nebiolo', price: '790', status: 'active', description: '100% Nebiolo' },

{ menu: 'Vino', categorie: "Blancos", name: 'Sto Tomas Sauvignon Blanc', price: '420,120', status: 'active', description: '100% Sauvinong Blanc' },
{ menu: 'Vino', categorie: "Blancos", name: 'Vinia Abril Sauvinong Blanc', price: '485,', status: 'active', description: '100% Sauvinong Blanc' },
{ menu: 'Vino', categorie: "Blancos", name: 'EMV Chardonay', price: '560, 130', status: 'active', description: '100% Chardonay' },

{ menu: 'Vino', categorie: "Rosados", name: 'Baron Balche Reseva Especial', price: '1250', status: 'active', description: '60% Palomino, 20% Grenache y 20% Mision' },
{ menu: 'Vino', categorie: "Rosados", name: 'Baron Balche Reseva Especial', price: '495,115', status: 'active', description: '100% Mourvedre' },
{ menu: 'Vino', categorie: "Rosados", name: 'Sto Tomas Rosado Mexico', price: '620,135', status: 'active', description: '100% Grenache' },
]